# codecov.yml example for R package

codecov:
  require_ci_to_pass: yes
  token: ea6efa89-bf95-4dcb-bd27-b6050ad09b1a

coverage:
  precision: 2
  round: down
  range: "70...100"
  path: file.path(Sys.getenv("RUNNER_TEMP"), "package")

comment:
  layout: "reach, diff, flags, files"
  behavior: "default"
  require_changes: yes



